apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: front
    env: dev
spec:
  containers:
  - name: cont1
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    app: front
    env: dev
spec:
  containers:
  - name: cont1
    image: nginx:latest